### ISSUE TITLE
TOML 0.5.0

### ISSUE THREAD

**Issue by 89z** [just95/toml.dart#11]
Newer versions of TOML support this syntax:

~~~
date = 1984-10-01
~~~

Since version 0.5.0 (Jul 2018):

https://toml.io/en/v0.5.0#local-date

**Comment by just95** [comment]
Thanks for the reminder. `toml.dart` only supports TOML 0.4.0 at the moment. I'm currently working on the internals of the package but I'm planning to upgrade to TOML 0.5.0 in early 2021.

**Comment by just95** [comment]
I've published [version 0.8.0 of `toml.dart`](https://pub.dev/packages/toml/versions/0.8.0) with support for [TOML 0.5.0](https://toml.io/en/v0.5.0) today.
