### ISSUE TITLE
Sound null safety support

### ISSUE THREAD

**Issue by erf** [just95/toml.dart#18]
Do you plan to add sound null safety support to Toml? 

Read more here:
https://dart.dev/null-safety

**Comment by just95** [comment]
My current plan was to work on null safety after the update to TOML 1.0.0 such that we have an up to date version of the package for SDK versions prior to 2.12.0. However, I can try to add a prerelease if you need one.

**Comment by erf** [comment]
Sounds good. No rush.

**Comment by erf** [comment]
I tried to update some packages now and i noticed `google_sign_in` had a dependency to `quiver 3.0.0` which failed with the `toml` dependency to a earlier version. Do you plan to update the dependencies to latest (null safe) ?

**Comment by just95** [comment]
Today I've released version [0.9.1](https://pub.dev/packages/toml/versions/0.9.1) which supports [TOML 1.0.0](https://toml.io/en/v1.0.0) as well as version [0.10.0](https://pub.dev/packages/toml/versions/0.10.0) which supports null safety.

**Comment by erf** [comment]
Great work.. I will update my `toml_localization` package now to null-safety.
