### ISSUE TITLE
Get up to date

### ISSUE THREAD

**Issue by erf** [just95/toml.dart#4]
Hey, do you have any plans to update this library? It seem to be one of the few `toml` libraries for dart, but it has aged a bit, dart sdk is now on version `2.8.0`, and the other packages are a bit outdated too. I tried to update the packages but there seem to be a few build issues. Also would be nice to add it to `pub.dev` as a package there. Thanks!

**Comment by just95** [comment]
Hi, I'm very sorry that I've neglected this library for such a long time. I'm still following the developments in the TOML community and was hoping to update `toml.dart` at some point (especially now that the spec is approaching 1.0). Unfortunately, university was keeping me quite busy for the past couple of years and I haven't really worked much with Dart in consequence. However, I'd like to checkout Dart 2 and updating this library may be a good opportunity to do so. I've no idea how difficult it will be to migrate to Dart 2 but I'll do some research and testing over the weekend. However, I cannot make any promises how long it will take until we have a working version again.

The package is on `pub.dev` by the way: https://pub.dev/packages/toml
However, since it is Dart 2 incompatible and has a very low score, it does not seem to be listed in the search results.

**Comment by erf** [comment]
Hey, no worries! It's cool that you want to have a look at it again. Dart have been developing pretty fast because of Flutter. I have been looking in Flutter lately. Maybe i can help out in some way. I have a [branch](https://github.com/erf/toml.dart/tree/update-packages) with an updated pubspec yaml and gitignore. You could perhaps do a `pub create` to re-create some missing items. `JSON` and `UTF8` are now in lower case. Is there a spesific reason you include the `yaml` package - could it be a `dev-dependency`?

**Comment by just95** [comment]
Sure, I'd appreciate a pull request : )

The dependency on the `yaml` package is mostly needed for tests and could be a `dev-dependency` in theory. However, when I created the library, I originally used [`dart_config`](https://github.com/chrisbu/dart_config) and when I moved away from that library, I recreated most of `dart_config`s functionality including the [`YamlConfigDecoder`](https://github.com/just95/toml.dart/blob/master/lib/decoder/yaml.dart). Thus, it is actually possible to load YAML files using the interface provided by `toml.dart` as well. Today I'm not sure anymore whether that's a good design decision and may drop YAML support (and therefore the `yaml` dependency) in the future.

Thanks : ) 
I actually just learned about [extension methods](https://dart.dev/guides/language/extension-methods) :exploding_head: :joy:

**Comment by erf** [comment]
I made a PR ( it does not build though but.. )

I think less dependencies is a good thing if possible, so if you can move yaml as a dev-dependency i think that would be good. btw what do you need config for? and if you need config, why not use TOML format?  

`extension methods` are really cool, and very tempting to use everywhere :D ..but they could pollute and make APIs crash across libraries. e.g. if two libraries make the same extension on String.

`dart2native` is also very interesting as you can have massive performance for scripts, servers etc. I also enjoy streams and async await, but i guess these are not that new..?

**Comment by erf** [comment]
oh with `dart 2.8`, you can write ` flutter pub outdated` to see outdated packages. You can also create and re-create packages with ` flutter pub create`. and if you use Android Studio, you can use the "Flutter Enhancment Suite" Plugin to easliy see which packages needs update and update them.

**Comment by just95** [comment]
> I think less dependencies is a good thing if possible, so if you can move yaml as a dev-dependency i think that would be good.

I agree. However, my main priority for now is to get the library to build again. We can consider architectural changes later : ) 

> what do you need config for?

The TOML spec contains some [pairs of `yaml` and `toml` files](https://github.com/toml-lang/toml/tree/master/tests) for testing purposes. Some of them are [part of the test suite](https://github.com/just95/toml.dart/tree/master/test/config) of `toml.dart`.

> you can write `flutter pub outdated` to see outdated packages

Thanks for the tip. I consider to setup a CI pipeline once everything is working again. That command could get handy then.

**Comment by erf** [comment]
You also no longer need to use the `new` keyword, and you can format the code using `flutter format`. I made a new PR with two commits for these

**Comment by erf** [comment]
I guess we are up to date now, so feel free to close this. I mentioned some nitpicks, but i'll let you sort those out. Btw [this](https://dart.dev/guides/language/effective-dart/style) is a pretty good read.

You mentioned a possbile loader for Flutter.. i wonder if it would make sense to perhaps separate the loading and the parsing into two separate libraries / packages? To make the parsing one, more focused, and have less dependencies?

**Comment by erf** [comment]
I noticed you pushed some changes. Are you planning a new release on pub.dev soonish?
