### ISSUE TITLE
Solve package conflicts with Flutter project

### ISSUE THREAD

**Issue by erf** [just95/toml.dart#7]
I tried to add `toml.dart` as a git dependency to a new Flutter project and then call `flutter packages get`, but i get a depencency issue:

```
Because every version of flutter_test from sdk depends on petitparser 2.4.0 and every version of toml from git depends on petitparser ^3.0.2, flutter_test from sdk is incompatible with toml from git.
So, because toml_flutter_test depends on both toml from git and flutter_test any from sdk, version solving failed.
```

I'll make a PR shortly

**Comment by erf** [comment]
See #8

**Comment by just95** [comment]
Thanks. I've merged your pull request. However, it looks like the dependency on `petitparser` of `flutter_test` [will be removed](https://github.com/flutter/flutter/commit/efdce3cf728c96d47e216120512595e8d9a3022b#diff-6db519d06b539bb165a44ad589217e9eL43) in one of the upcoming releases of the Flutter SDK. Thus, I'll leave this issue open as a reminder for ourselves that `petitparser` should be upgraded once Flutter has been updated.

**Comment by erf** [comment]
Ok, great. Do you plan to publish a new release soon?

**Comment by erf** [comment]
Btw, it does seem annoying that we will have to keep up to date with dependencies based on what Flutter SDK uses - i wonder if there is a better way to do this.. will do some testing.

Also, would be cool to include a Flutter project in the example folder, but right now i think it will be a problem with the existing files.

**Comment by just95** [comment]
> Do you plan to publish a new release soon?

Sure, since all tests in the `test` directory are currently passing and all examples in `example` are building without errors, I think we could release the current state. However, some new tests have been added to [toml-test](https://github.com/BurntSushi/toml-test) which are not passing at the moment. Thus, I'm not sure whether we should tag the release as `0.6.0` or indicate in the version that there are known bugs (i.e., that this is something like a beta version). 

> would be cool to include a Flutter project in the example folder, but right now i think it will be a problem with the existing files.

I like the idea of adding a Flutter example. I'll move the existing examples into subdirectories (probably after I did the release). Since I don't have the Flutter SDK setup on my PC right now, it would be nice if you could prepare a small example and create a pull request : )

**Comment by erf** [comment]
Are the new failing tests related to new Toml specs? I think pushing a new release now should be fine, and then make those tests run later.

Sounds good. I’ll add an example once you clean up that example folder :)

**Comment by just95** [comment]
> Are the new failing tests related to new Toml specs?

No, I don't think so. For example, the following is is currently accepted by the parser even though is not valid in TOML 0.4.0.

```toml
[table] key = "value"
```

I am currently working on a parser based on the ABNF which should hopefully fix the failing test cases.

> I think pushing a new release now should be fine, and then make those tests run later.

I've now published [version 0.6.0](https://pub.dev/packages/toml) and cleaned up the `example` directory.

**Comment by erf** [comment]
BTW, I noticed the [pub analysic](https://pub.dev/packages/toml#-analysis-tab-) that there are some `Healt Suggestions` which will improve the pub.dev score, might worth looking into.

**Comment by just95** [comment]
Yeah, I've noticed those suggestions, too. Most of them look easy to fix. I have no idea, though, why `dartdoc` failed. I don't get the same error locally.

**Comment by erf** [comment]
Not sure about the dart docs. It builds locally for me also. There is probably some issue with the pub.dev build server. You can see documentation failed under [versions](https://pub.dev/packages/toml/versions) with some info.

Just a curiosity, if i call `flutter create -t package .` in the root folder, after renaming `dart.toml` to `toml` (a valid Flutter package name), it create a `.metadata` file, not sure if that is missing or only needed for Flutter packages.
